[package]
name = "{{project-name}}"
version = "0.1.0"
authors = ["{{authors}}"]
edition = "2018"

[dependencies]
actix-web = {version="3.2.0", features=["rustls"]}
log = "0.4.14"
serde = "1.0.117"
simple_logger = "1.11.0"
structopt = "0.3.21"
